services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: julienne123
      POSTGRES_DB: produit

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080

  produit-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: produit-container
    restart: always
    ports:
      - 8081:8000
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/produit
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: julienne123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - postgres

