services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: julienne123
      POSTGRES_DB: produit

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080

